### ISSUE TITLE
Improve logger output when tasks fail

### ISSUE THREAD

**Issue by sgoodm** [aiddata/geo-datasets#110]
Right now we have minimal (if any) indication that individual / not all tasks succeeded. The ResultTuple should already accomplish nearly all of what we want logged (see https://github.com/aiddata/geo-datasets/blob/develop/global_scripts/dataset.py#L41) so we just need some logic around checking if anything failed, calling the ResultTuple __repr__, generating a warning, etc.

**Comment by jacobwhall** [comment]
Resolved in #116
