### ISSUE TITLE
modis_lst

### ISSUE THREAD

**Issue by sgoodm** [aiddata/geo-datasets#149]
Core work done in #101 

- [x] Update from v6 to v6.1 done in #145
- [x] Convert to COG output and test
- [x] Test with Prefect deployments
- [x] incorporate use of intermediate local dirs for download/processing

**Comment by sgoodm** [comment]
2d8040dfb4ea5cedd7de8c147aba6032cb388b0a adds use of temp dir for downloads, but left processing stage write to final dir since it is not an open IO stream that could take an extended period of time

**Comment by sgoodm** [comment]
Full test and run for v6.1, just needs ingest (new / updated ingest json as well)

Need to decide whether to remove old dataset in GeoQuery once this is active

**Comment by sgoodm** [comment]
Ingested

**Comment by jacobwhall** [comment]
I modis_lst is in a good spot now, with a recent deployment on nova running smoothly.
